services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "12G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /var/win:/storage
    networks:
      _host:
        ipv4_address: 172.11.0.2
      _external:
        ipv4_address: 172.12.0.3
networks:
  _host:
    name: radminvpn_internal
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.11.0.0/16
        gateway: 172.11.0.1
  _external:
    name: radminvpn_external
    ipam:
      driver: default
      config:
      - subnet: 172.12.0.0/16
        gateway: 172.12.0.1
