services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win7"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "12G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /var/win:/storage
    networks:
      radminvpnonlinuxalternative_host:
        ipv4_address: 172.27.0.2
      radminvpnonlinuxalternative_external:
        ipv4_address: 172.28.0.3

networks:
  radminvpnonlinuxalternative_host:
    name: radminvpnonlinuxalternative_host
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.27.0.0/16
  radminvpnonlinuxalternative_external:
    name: radminvpnonlinuxalternative_external
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16